/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ephotostudio.photographer;
import java.sql.*;
/**
 *
 * @author Dell
 */
public class Photographer_Main extends javax.swing.JFrame {

    /**
     * Creates new form Photographer_Main
     */
    public Photographer_Main() {
        initComponents();
    }
    
    /*public void bindLbl(String data){
        lbl.setText(data);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_lbl = new javax.swing.JLabel();
        customers = new javax.swing.JButton();
        edit_profile_photographer = new javax.swing.JButton();
        gallary_photographer = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        view_profile_photographer = new javax.swing.JButton();
        add_customers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Photostudio(Photographer Dashboard)");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        welcome_lbl.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N

        customers.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        customers.setText("Your Customers");
        customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersActionPerformed(evt);
            }
        });

        edit_profile_photographer.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        edit_profile_photographer.setText("Edit Profile");
        edit_profile_photographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_photographer_profile_photographerActionPerformed(evt);
            }
        });

        gallary_photographer.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        gallary_photographer.setText("Gallary");
        gallary_photographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gallary_photographerActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        logout.setText("Logut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        view_profile_photographer.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        view_profile_photographer.setText("View Profile");
        view_profile_photographer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_profile_photographer_profile_photographerActionPerformed(evt);
            }
        });

        add_customers.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        add_customers.setText("Add Customers");
        add_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_customersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit_profile_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gallary_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_profile_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcome_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_profile_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(add_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit_profile_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gallary_photographer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gallary_photographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gallary_photographerActionPerformed
        Photographer_Gallary.main(new String[]{});
        dispose();
    }//GEN-LAST:event_gallary_photographerActionPerformed

    private void customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersActionPerformed
        /*Photographer_Customers cm = new Photographer_Customers();
        cm.bindMyCustomers(Photographer_Login.id);
        cm.setVisible(true);
        cm.setLocationRelativeTo(null);*/
        Photographer_Customers.main(new String[]{});
        dispose();
    }//GEN-LAST:event_customersActionPerformed

    private void edit_profile_photographer_profile_photographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_photographer_profile_photographerActionPerformed
        Photographer_Edit_Profile.main(new String[]{});
        dispose();
    }//GEN-LAST:event_edit_profile_photographer_profile_photographerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Photographer_Login.main(new String[]{});
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void view_profile_photographer_profile_photographerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_profile_photographer_profile_photographerActionPerformed
        Photographer_View_Profile.main(new String[]{});
        dispose();
    }//GEN-LAST:event_view_profile_photographer_profile_photographerActionPerformed

    private void add_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_customersActionPerformed
        Photographer_Add_Customers.main(new String[]{});
        dispose();
    }//GEN-LAST:event_add_customersActionPerformed

    public static void main(String args[]) 
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/e_photostudio","root","root");
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("select * from details where id="+Photographer_Login.id);
            while(rs.next())
            {
                first_name=rs.getString("fn");
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Photographer_Main().setVisible(true);
                welcome_lbl.setText("Welcome "+first_name);
            }
        });
    }
    public static String first_name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_customers;
    private javax.swing.JButton customers;
    private javax.swing.JButton edit_profile_photographer;
    private javax.swing.JButton gallary_photographer;
    private javax.swing.JButton logout;
    private javax.swing.JButton view_profile_photographer;
    private static javax.swing.JLabel welcome_lbl;
    // End of variables declaration//GEN-END:variables
}
