/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ephotostudio.photographer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;


public class Photographer_Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    public Photographer_Customers() {
        initComponents();
    }
    
    public void bindMyCustomers() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/e_photostudio", "root", "root");
            Statement s = c.createStatement();
            
            ResultSet rs = s.executeQuery("SELECT first_name AS 'First Name',last_name AS 'Last Name',mobile_no AS 'Contact No.',email_id AS 'Email',order_status AS 'Order Status',bill AS 'Bill' FROM customers WHERE ph_id="+Photographer_Login.id);
            /*while(rs.next()){
            System.out.println("Hello");
            System.out.println(rs.getString(0));
            }*/
            tblCustomers.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        edit_customer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Photostudio(Customers)");
        setLocation(new java.awt.Point(500, 200));

        tblCustomers.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblCustomers);

        title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        title.setText("Your Customers");

        done.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        edit_customer.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit_customer.setText("Edit");
        edit_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_customerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 192, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(edit_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(done)
                    .addComponent(edit_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        Photographer_Main.main(new String[]{});
        dispose();
    }//GEN-LAST:event_doneActionPerformed

    private void edit_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_customerActionPerformed
        Photographer_Identify_Customer.main(new String[]{});
        dispose();
    }//GEN-LAST:event_edit_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Photographer_Customers cm = new Photographer_Customers();
        cm.bindMyCustomers();
        cm.setVisible(true);
        cm.title.setText("Welcome "+Photographer_Login.login_user_name);
      
        /*java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        //new Photographer_Customers().setVisible(true);
        }
        });*/
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JButton edit_customer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
