/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ephotostudio.photographer;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class Photographer_Add_Customers extends javax.swing.JFrame {

    /**
     * Creates new form Photographer_Add_Customers
     */
    public Photographer_Add_Customers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        first_name = new javax.swing.JLabel();
        first_name_text = new javax.swing.JTextField();
        last_name = new javax.swing.JLabel();
        last_name_text = new javax.swing.JTextField();
        mobile_number = new javax.swing.JLabel();
        mobile_number_text = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        email_text = new javax.swing.JTextField();
        order_status = new javax.swing.JLabel();
        completed = new javax.swing.JRadioButton();
        pending = new javax.swing.JRadioButton();
        canceled = new javax.swing.JRadioButton();
        bill = new javax.swing.JLabel();
        bill_text = new javax.swing.JTextField();
        add_customer = new javax.swing.JButton();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Photostudio(Add Customers)");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        title.setText("Add Customers");

        first_name.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        first_name.setText("First Name");

        first_name_text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        last_name.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        last_name.setText("Last Name");

        last_name_text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mobile_number.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        mobile_number.setText("Mobile Number");

        mobile_number_text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        email.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        email.setText("Email");

        email_text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        order_status.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        order_status.setText("Order status");

        buttonGroup.add(completed);
        completed.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        completed.setText("Completed");

        buttonGroup.add(pending);
        pending.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        pending.setText("Pending");

        buttonGroup.add(canceled);
        canceled.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        canceled.setText("Canceled");

        bill.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        bill.setText("Bill");

        bill_text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_textActionPerformed(evt);
            }
        });

        add_customer.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        add_customer.setText("Add");
        add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_customerActionPerformed(evt);
            }
        });

        done.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(order_status))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mobile_number)
                            .addComponent(last_name)
                            .addComponent(first_name)
                            .addComponent(email))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mobile_number_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(last_name_text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_name_text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_text)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(add_customer)
                                .addGap(38, 38, 38)
                                .addComponent(done))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bill)
                                .addGap(26, 26, 26)
                                .addComponent(bill_text, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(completed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pending)
                                .addGap(14, 14, 14)
                                .addComponent(canceled))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_number, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(mobile_number_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order_status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completed)
                    .addComponent(pending)
                    .addComponent(canceled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill)
                    .addComponent(bill_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_customer)
                    .addComponent(done))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bill_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_textActionPerformed

    private void add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_customerActionPerformed
        String order_status=null;
        if(completed.isSelected())
        {
            order_status="Completed";
        }
        else if(pending.isSelected())
        {
            order_status="Pending";
        }
        else
        {
            order_status="Canceled";
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/e_photostudio","root","root");
           Statement s=c.createStatement();
            s.execute("insert into customers(first_name,last_name,mobile_no,email_id,order_status,bill,ph_id) "
                    + "values('"+first_name_text.getText()+"','"+last_name_text.getText()+"','"+mobile_number_text.getText()+"','"+email_text.getText()+"',"
                            + "'"+order_status+"','"+bill_text.getText()+"','"+Photographer_Login.id+"')");
            JOptionPane.showMessageDialog(add_customer,"Customer Added Successfullly");
            first_name_text.setText("");
            last_name_text.setText("");
            mobile_number_text.setText("");
            email_text.setText("");
            buttonGroup.clearSelection();
            bill_text.setText("");
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(add_customer,"Sorry Can't Add Customer!!!");
            first_name_text.setText("");
            last_name_text.setText("");
            mobile_number_text.setText("");
            email_text.setText("");
            buttonGroup.clearSelection();
            bill_text.setText("");
        }
    }//GEN-LAST:event_add_customerActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        Photographer_Main.main(new String[]{});
        dispose();
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Photographer_Add_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Photographer_Add_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Photographer_Add_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Photographer_Add_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Photographer_Add_Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_customer;
    private javax.swing.JLabel bill;
    private javax.swing.JTextField bill_text;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton canceled;
    private javax.swing.JRadioButton completed;
    private javax.swing.JButton done;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_text;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField first_name_text;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField last_name_text;
    private javax.swing.JLabel mobile_number;
    private javax.swing.JTextField mobile_number_text;
    private javax.swing.JLabel order_status;
    private javax.swing.JRadioButton pending;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
